set -g mouse on
set -g base-index 1
set -g renumber-windows on
set -g focus-events on

# Set Clipboard
set -g set-clipboard on
# Switch to Vim key-bindings.
set -g mode-keys vi
# Set 'v' to begin selection & 'y' to yank.
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# Vim Pane Navigation.
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

## Status Bar
set -g status-left-length 30
set -g status-bg black
set -g status-fg white
set -g window-status-current-style bg=colour202

## Panes
set -g pane-border-style fg=white
set -g pane-active-border-style fg=colour202

## Reload
bind r source-file ~/.tmux.conf
