#!/usr/bin/env bash

path=$(pwd)
session_name=$(basename "${path}")

tmux new-session -d -s "${session_name}"

tmux rename-window -t "${session_name}":1 "main"
tmux send-keys -t "${session_name}":1.0 "cd ${path} && clear" C-m

tmux new-window -t "${session_name}":2 -n "editor"
tmux send-keys -t "${session_name}":2.0 "cd ${path} && nvim" C-m

tmux select-window -t "${session_name}":2
tmux attach-session -t "${session_name}"
